name: 'VR&R'
favicon: null
layout_spectrum: 0.01057
typography_spectrum: 0.71851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ef4b41'
    - '#fbdddb'
    - '#f1776e'
    - '#f8bab6'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
