name: 'VR&R'
favicon: null
layout_spectrum: 0.4636494042351842
typography_spectrum: 0.5095796613022685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6252669070381671
  lightness: 0.5671681670937687
  saturation: 0.957386854570359
  rhythmicContrast: 0.7571322009898722
purpose: []
